### ISSUE TITLE
Sidebar not working on Android

### ISSUE THREAD

**Issue by Fire69** [swttt/homeydash-v3#7]
Tested with Chrome on Android 6 phone and Android 5 tablet.
When the dashboard opens, the sidebar is visible.
But when you slide left or right, it closes.
Sliding left or right doesn't bring it back anymore.

When using the built-in browser for Samsung ('Internet'), it works.
On Windows10 laptop with Chrome it's working also.

**Comment by swttt** [comment]
Fixed!
